//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2013 - Infos @ http://www.17buddies.net //
//          More than 85000 maps to download!           //
//////////////////////////////////////////////////////////
// Map Name  : gg_bk_courtyard_v1
// Download @: http://www.17buddies.net/17b2/View/Map/70026/gg_bk_courtyard_v1.html
// (.res file generated with script version 3.0)
//////////////////////////////////////////////////////////
// Wad files legend:
//     *  : Hardcoded in bsp file, this wad was found (in
//          archive or on 17Buddies's website) but doesn't
//          contains any used texture.
//          However, this file may be necessary.
//     ** : Hardcoded in bsp file, this wad could not be
//          found (neither in archive nor on 17Buddies's
//          website) and thus could not be analysed.
//          However, this file may be necessary.
//////////////////////////////////////////////////////////
"resources"
{
"materials/tools/toolsnodraw.vmt" "file"
"materials/tools/toolsnodraw.vtf" "file"
"materials/stone/infflrd.vmt" "file"
"materials/stone/infflrd.vtf" "file"
"materials/tools/toolsskybox.vmt" "file"
"materials/tools/toolsskybox.vtf" "file"
"materials/cs_italy/marketwall02.vmt" "file"
"materials/cs_italy/marketwall02.vtf" "file"
"materials/de_piranesi/pi_intrimb2.vmt" "file"
"materials/de_piranesi/pi_intrimb2.vtf" "file"
"materials/stone/infwllf.vmt" "file"
"materials/stone/infwllf.vtf" "file"
"materials/plaster/plasterceiling002b.vmt" "file"
"materials/plaster/plasterceiling002b.vtf" "file"
"materials/stone/infwllcedge.vmt" "file"
"materials/stone/infwllcedge.vtf" "file"
"materials/stone/infwllc.vmt" "file"
"materials/stone/infwllc.vtf" "file"
"materials/tools/toolshint.vmt" "file"
"materials/tools/toolshint.vtf" "file"
"materials/tools/toolsskip.vmt" "file"
"materials/tools/toolsskip.vtf" "file"
"materials/de_chateau/exttrim04.vmt" "file"
"materials/de_chateau/exttrim04.vtf" "file"
"materials/nature/milmountains002.vmt" "file"
"materials/nature/milmountains002.vtf" "file"
"materials/nature/milmountains003.vmt" "file"
"materials/nature/milmountains003.vtf" "file"
"materials/nature/milmountains004.vmt" "file"
"materials/nature/milmountains004.vtf" "file"
"materials/nature/milmountains001.vmt" "file"
"materials/nature/milmountains001.vtf" "file"
"materials/wood/inffence01.vmt" "file"
"materials/wood/inffence01.vtf" "file"
"materials/de_cbble/trim05.vmt" "file"
"materials/de_cbble/trim05.vtf" "file"
"materials/concrete/concreteceiling003a.vmt" "file"
"materials/concrete/concreteceiling003a.vtf" "file"
"materials/de_tides/tides_roof_1.vmt" "file"
"materials/de_tides/tides_roof_1.vtf" "file"
"materials/nature/milground008.vmt" "file"
"materials/nature/milground008.vtf" "file"
"materials/de_piranesi/pi_wood1.vmt" "file"
"materials/de_piranesi/pi_wood1.vtf" "file"
"materials/de_cbble/cratesm01a.vmt" "file"
"materials/de_cbble/cratesm01a.vtf" "file"
"materials/de_cbble/cratesm01.vmt" "file"
"materials/de_cbble/cratesm01.vtf" "file"
"materials/concrete/concretewall006a.vmt" "file"
"materials/concrete/concretewall006a.vtf" "file"
"materials/de_piranesi/pi_archt64b.vmt" "file"
"materials/de_piranesi/pi_archt64b.vtf" "file"
"materials/de_aztec/wood_plank_7.vmt" "file"
"materials/de_aztec/wood_plank_7.vtf" "file"
"materials/stone/infflrtrima.vmt" "file"
"materials/stone/infflrtrima.vtf" "file"
"materials/stone/infflra.vmt" "file"
"materials/stone/infflra.vtf" "file"
"materials/plaster/infwlld.vmt" "file"
"materials/plaster/infwlld.vtf" "file"
"materials/tile/infflrb.vmt" "file"
"materials/tile/infflrb.vtf" "file"
"materials/brick/infwlla.vmt" "file"
"materials/brick/infwlla.vtf" "file"
"materials/de_cbble/cratebig01.vmt" "file"
"materials/de_cbble/cratebig01.vtf" "file"
"materials/de_cbble/cratebig01c.vmt" "file"
"materials/de_cbble/cratebig01c.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/liquids/infernowater_0_896_40.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/liquids/infernowater_0_896_40.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/liquids/infernowater_0_-896_40.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/liquids/infernowater_0_-896_40.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/liquids/infernowater_-128_0_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/liquids/infernowater_-128_0_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_864_-512_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_864_-512_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_544_-896_96.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_544_-896_96.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_640_-512_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_640_-512_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-864_512_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-864_512_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-544_896_96.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-544_896_96.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-640_512_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-640_512_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-864_-512_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-864_-512_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-544_-896_96.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-544_-896_96.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-640_-512_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-640_-512_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-640_-320_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-640_-320_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-576_-128_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-576_-128_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-640_320_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-640_320_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-576_128_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_-576_128_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_640_512_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_640_512_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_864_512_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_864_512_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_544_896_96.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_544_896_96.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_640_320_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_640_320_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_640_-320_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_640_-320_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_576_128_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_576_128_64.vtf" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_576_-128_64.vmt" "file"
"materials/maps/gg_bk_courtyard_v1/de_chateau/chatcolumn01_576_-128_64.vtf" "file"
"materials/dev/dev_waterbeneath2.vmt" "file"
"materials/dev/dev_waterbeneath2.vtf" "file"
}
