"resources"
{
"maps/scoutzknivez.bsp" "file"
"maps/scoutzknivez.res" "file"
"materials/simianbanner.vmt" "file"
"materials/simianbanner.vtf" "file"
"materials/top1.vmt" "file"
"materials/top1.vtf" "file"
"sound/admin_plugin/arrest1.wav" "file"
"sound/admin_plugin/bbgun1.wav" "file"
"sound/admin_plugin/bullshit.wav" "file"
"sound/admin_plugin/chopper.wav" "file"
"sound/admin_plugin/comeon.wav" "file"
"sound/admin_plugin/cut1.wav" "file"
"sound/admin_plugin/damn1.wav" "file"
"sound/admin_plugin/dream1.wav" "file"
"sound/admin_plugin/found1.wav" "file"
"sound/admin_plugin/giantcock1.wav" "file"
"sound/admin_plugin/holiday1.wav" "file"
"sound/admin_plugin/killme.wav" "file"
"sound/admin_plugin/ko1.wav" "file"
"sound/admin_plugin/paintchips1.wav" "file"
"sound/admin_plugin/sob.wav" "file"
"sound/admin_plugin/double1.wav" "file"
"sound/admin_plugin/ugly1.wav" "file"
"sound/admin_plugin/ow.wav" "file"
"sound/admin_plugin/lookgood.wav" "file"
"sound/admin_plugin/marvin4.wav" "file"
"sound/admin_plugin/breakfast2.wav" "file"
}


